name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore
      run: dotnet restore ./Todos.sln

    - name: Build
      run: dotnet build ./Todos.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Todos.sln --configuration Release --no-build
      
    
